### ISSUE TITLE
error install mgamal/laravel-inbox

### ISSUE THREAD

**Issue by hasanhadi** [mgamal92/inbox-laravel#2]
i have problem with install this package 
laravel version 10
php version ^8.1

In PackageDiscoveryTrait.php line 364:

  Could not find a matching version of package mgamal/laravel-inbox. Check the package spelling, your version constra
  int and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by hasanhadi** [comment]
The same problem can't install the package

**Comment by mgamal92** [comment]
We've moved this package to [this url](https://github.com/BaristaPHP/inbox-laravel), we will publish the first stable versions within the next few days. Thanks for you patience

**Comment by hasanhadi** [comment]
> We've moved this package to [this url](https://github.com/BaristaPHP/inbox-laravel), we will publish the first stable versions within the next few days. Thanks for you patience

can explain how can install this package using https://github.com/BaristaPHP/inbox-laravel
